image: gitlab.labs.g2-inc.net:4567/screamingbunny/docker/plus:alpine-python3

variables:
  GIT_SSL_NO_VERIFY: "true"
  PKG_DIR: ./
  DIST_DIR: ./dist

stages:
  - build

Build-Wheel:
  stage: build

  script:
    - pip wheel $PKG_DIR -w $DIST_DIR
    - mv $DIST_DIR/ScreamingBunny_Utils-*.whl .

  artifacts:
    expire_in: 4 weeks
    paths:
     - ./ScreamingBunny_Utils-*.whl
