image: gitlab.ad.tsdcloudprojects.com:5005/screamingbunny/docker/plus:alpine-python3

variables:
  GIT_SSL_NO_VERIFY: "true"
  PKG_DIR: ./
  DIST_DIR: ./dist

stages:
  - build

Build-Main:
  stage: build

  script:
    - cd root
    - python3 setup.py sdist bdist_wheel
    - mv $DIST_DIR/*.whl .

  artifacts:
    name: "SB_UTILS.${CI_PIPELINE_ID}_${CI_COMMIT_SHA:0:8}"
    expire_in: 1 weeks
    paths:
     - ./*.whl

Build-Twisted:
  stage: build

  script:
    - cd twisted
    - python3 setup.py sdist bdist_wheel
    - mv $DIST_DIR/*.whl .

  artifacts:
    name: "SB_UTILS.${CI_PIPELINE_ID}_${CI_COMMIT_SHA:0:8}"
    expire_in: 1 weeks
    paths:
     - ./*.whl