"""
OSQuery osquery_schedule ORM
"""
from osquery_orm.orm import BaseModel
from peewee import IntegerField, BigIntegerField, TextField


class OsquerySchedule(BaseModel):
    """
    Information about the current queries that are scheduled in osquery.
    """
    # The given name for this query
    name = TextField()
    # The exact query to run
    query = TextField()
    # The interval in seconds to run this query, not an exact interval
    interval = IntegerField()
    # Number of times the query was executed
    executions = BigIntegerField()
    # UNIX time stamp in seconds of the last completed execution
    last_executed = BigIntegerField()
    # 1 if the query is denylisted else 0
    denylisted = IntegerField()  # {'aliases': ['blacklisted']}
    # Total number of bytes generated by the query
    output_size = BigIntegerField()
    # Total wall time spent executing
    wall_time = BigIntegerField()
    # Total user time spent executing
    user_time = BigIntegerField()
    # Total system time spent executing
    system_time = BigIntegerField()
    # Average private memory left after executing
    average_memory = BigIntegerField()

    class Meta:
        table_name = "osquery_schedule"
